/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-pages-config.ts
 */

import { PageConfig, PlatformConfig } from '../models';

export const GENERATED_PAGES_CONFIG: Record<string, PageConfig> = {
  "agents": {
    "id": "agents",
    "label": "Agents",
    "icon": "@tui.bot",
    "title": "Agents Configuration",
    "description": "Select skills, technologies, and tooling for your AI agents.",
    "categories": [
      {
        "id": "conventions",
        "title": "Core Architecture",
        "icon": "@tui.shield-check",
        "type": "checkbox",
        "order": 1,
        "items": [
          {
            "id": "clean-architecture",
            "label": "Clean Architecture",
            "filePath": "assets/pages/agents/conventions/clean-architecture.json",
            "recommendedWith": [
              "solid",
              "strict-typing"
            ]
          },
          {
            "id": "solid",
            "label": "Solid",
            "filePath": "assets/pages/agents/conventions/solid.json",
            "recommendedWith": [
              "clean-architecture",
              "strict-typing"
            ]
          }
        ]
      },
      {
        "id": "frontend",
        "title": "Client-Side Ecosystem",
        "icon": "@tui.layout",
        "type": "checkbox",
        "order": 2,
        "items": [
          {
            "id": "angular",
            "label": "Angular",
            "filePath": "assets/pages/agents/frontend/angular.json",
            "recommendedWith": [
              "typescript",
              "jest",
              "eslint"
            ],
            "discouragedWith": [
              "react",
              "vue"
            ]
          },
          {
            "id": "javascript",
            "label": "Javascript",
            "filePath": "assets/pages/agents/frontend/javascript.json",
            "recommendedWith": [
              "eslint"
            ],
            "discouragedWith": [
              "strict-typing"
            ]
          },
          {
            "id": "react",
            "label": "React",
            "filePath": "assets/pages/agents/frontend/react.json",
            "recommendedWith": [
              "typescript",
              "javascript",
              "jest"
            ],
            "discouragedWith": [
              "angular",
              "vue"
            ]
          },
          {
            "id": "typescript",
            "label": "Typescript",
            "filePath": "assets/pages/agents/frontend/typescript.json",
            "recommendedWith": [
              "eslint",
              "strict-typing"
            ]
          },
          {
            "id": "vue",
            "label": "Vue",
            "filePath": "assets/pages/agents/frontend/vue.json",
            "recommendedWith": [
              "typescript",
              "javascript",
              "vitest"
            ],
            "discouragedWith": [
              "angular",
              "react"
            ]
          }
        ]
      },
      {
        "id": "backend",
        "title": "Server-Side Ecosystem",
        "icon": "@tui.server",
        "type": "checkbox",
        "order": 3,
        "items": [
          {
            "id": "express",
            "label": "Express",
            "filePath": "assets/pages/agents/backend/express.json",
            "recommendedWith": [
              "javascript",
              "typescript",
              "mongodb"
            ],
            "discouragedWith": [
              "nestjs",
              "spring-boot",
              "php"
            ]
          },
          {
            "id": "nestjs",
            "label": "Nestjs",
            "filePath": "assets/pages/agents/backend/nestjs.json",
            "recommendedWith": [
              "typescript",
              "postgresql",
              "docker"
            ],
            "discouragedWith": [
              "spring-boot",
              "php",
              "express"
            ]
          },
          {
            "id": "php",
            "label": "Php",
            "filePath": "assets/pages/agents/backend/php.json",
            "recommendedWith": [
              "mongodb",
              "redis"
            ],
            "discouragedWith": [
              "nestjs",
              "spring-boot",
              "express"
            ]
          },
          {
            "id": "spring-boot",
            "label": "Spring Boot",
            "filePath": "assets/pages/agents/backend/spring-boot.json",
            "recommendedWith": [
              "postgresql",
              "docker"
            ],
            "discouragedWith": [
              "nestjs",
              "express",
              "php"
            ]
          }
        ]
      },
      {
        "id": "database",
        "title": "Data Layer",
        "icon": "@tui.database",
        "type": "checkbox",
        "order": 4,
        "items": [
          {
            "id": "mongodb",
            "label": "Mongodb",
            "filePath": "assets/pages/agents/database/mongodb.json",
            "recommendedWith": [
              "express",
              "javascript"
            ]
          },
          {
            "id": "postgresql",
            "label": "Postgresql",
            "filePath": "assets/pages/agents/database/postgresql.json",
            "recommendedWith": [
              "nestjs",
              "spring-boot",
              "strict-typing"
            ]
          },
          {
            "id": "redis",
            "label": "Redis",
            "filePath": "assets/pages/agents/database/redis.json",
            "recommendedWith": [
              "nestjs",
              "docker"
            ]
          }
        ]
      },
      {
        "id": "mobile",
        "title": "Mobile Development",
        "icon": "@tui.smartphone",
        "type": "checkbox",
        "order": 5,
        "items": [
          {
            "id": "flutter",
            "label": "Flutter",
            "filePath": "assets/pages/agents/mobile/flutter.json",
            "recommendedWith": [
              "docker"
            ],
            "discouragedWith": [
              "react-native",
              "swift"
            ]
          },
          {
            "id": "react-native",
            "label": "React Native",
            "filePath": "assets/pages/agents/mobile/react-native.json",
            "recommendedWith": [
              "react",
              "typescript",
              "jest"
            ],
            "discouragedWith": [
              "flutter",
              "swift"
            ]
          },
          {
            "id": "swift",
            "label": "Swift",
            "filePath": "assets/pages/agents/mobile/swift.json",
            "discouragedWith": [
              "flutter",
              "react-native"
            ]
          }
        ]
      },
      {
        "id": "tooling",
        "title": "Tooling & Quality",
        "icon": "@tui.wrench",
        "type": "checkbox",
        "order": 6,
        "items": [
          {
            "id": "docker",
            "label": "Docker",
            "filePath": "assets/pages/agents/tooling/docker.json",
            "recommendedWith": [
              "github-actions",
              "nestjs"
            ]
          },
          {
            "id": "github-actions",
            "label": "Github Actions",
            "filePath": "assets/pages/agents/tooling/github-actions.json",
            "recommendedWith": [
              "docker",
              "eslint"
            ]
          },
          {
            "id": "jest",
            "label": "Jest",
            "filePath": "assets/pages/agents/tooling/jest.json",
            "recommendedWith": [
              "typescript",
              "eslint"
            ],
            "discouragedWith": [
              "vitest"
            ]
          }
        ]
      }
    ]
  },
  "rules": {
    "id": "rules",
    "label": "Rules",
    "icon": "@tui.shield-check",
    "title": "Project Rules",
    "description": "Configure standard engineering rules and constraints.",
    "categories": [
      {
        "id": "conventions",
        "title": "Core Architecture",
        "icon": "@tui.shield-check",
        "type": "checkbox",
        "order": 1,
        "items": [
          {
            "id": "clean-code",
            "label": "Clean Code",
            "filePath": "assets/pages/rules/conventions/clean-code.json",
            "recommendedWith": [
              "solid",
              "eslint"
            ]
          },
          {
            "id": "ddd",
            "label": "Ddd",
            "filePath": "assets/pages/rules/conventions/ddd.json",
            "recommendedWith": [
              "clean-architecture"
            ]
          },
          {
            "id": "fsd",
            "label": "Fsd",
            "filePath": "assets/pages/rules/conventions/fsd.json",
            "discouragedWith": [
              "hexagonal"
            ]
          },
          {
            "id": "hexagonal",
            "label": "Hexagonal",
            "filePath": "assets/pages/rules/conventions/hexagonal.json",
            "recommendedWith": [
              "clean-architecture"
            ],
            "discouragedWith": [
              "fsd"
            ]
          },
          {
            "id": "mvc",
            "label": "Mvc",
            "filePath": "assets/pages/rules/conventions/mvc.json"
          }
        ]
      },
      {
        "id": "code-quality",
        "title": "Code Quality Rules",
        "icon": "@tui.check-circle",
        "type": "checkbox",
        "order": 2,
        "items": [
          {
            "id": "strict-typing",
            "label": "Strict Typing",
            "filePath": "assets/pages/rules/code-quality/strict-typing.json",
            "recommendedWith": [
              "typescript",
              "eslint"
            ]
          },
          {
            "id": "zero-literals",
            "label": "Zero Literals",
            "filePath": "assets/pages/rules/code-quality/zero-literals.json",
            "recommendedWith": [
              "strict-typing"
            ]
          }
        ]
      },
      {
        "id": "security",
        "title": "Security Rules",
        "icon": "@tui.lock",
        "type": "checkbox",
        "order": 3,
        "items": [
          {
            "id": "auth-guards",
            "label": "Auth Guards",
            "filePath": "assets/pages/rules/security/auth-guards.json",
            "recommendedWith": [
              "xss-protection"
            ]
          },
          {
            "id": "xss-protection",
            "label": "Xss Protection",
            "filePath": "assets/pages/rules/security/xss-protection.json",
            "recommendedWith": [
              "auth-guards"
            ]
          }
        ]
      },
      {
        "id": "tooling",
        "title": "Tooling & Quality",
        "icon": "@tui.wrench",
        "type": "checkbox",
        "order": 4,
        "items": [
          {
            "id": "eslint",
            "label": "Eslint",
            "filePath": "assets/pages/rules/tooling/eslint.json",
            "recommendedWith": [
              "prettier",
              "typescript"
            ]
          },
          {
            "id": "husky",
            "label": "Husky",
            "filePath": "assets/pages/rules/tooling/husky.json",
            "recommendedWith": [
              "eslint",
              "prettier"
            ]
          },
          {
            "id": "jest",
            "label": "Jest",
            "filePath": "assets/pages/rules/tooling/jest.json",
            "recommendedWith": [
              "typescript",
              "eslint"
            ],
            "discouragedWith": [
              "vitest"
            ]
          },
          {
            "id": "prettier",
            "label": "Prettier",
            "filePath": "assets/pages/rules/tooling/prettier.json",
            "recommendedWith": [
              "eslint",
              "husky"
            ]
          },
          {
            "id": "vitest",
            "label": "Vitest",
            "filePath": "assets/pages/rules/tooling/vitest.json",
            "recommendedWith": [
              "vue",
              "typescript"
            ],
            "discouragedWith": [
              "jest"
            ]
          }
        ]
      }
    ]
  },
  "workflows": {
    "id": "workflows",
    "label": "Workflows",
    "icon": "@tui.git-merge",
    "title": "Workflows",
    "description": "Select standard operational workflows for your team.",
    "categories": [
      {
        "id": "development",
        "title": "Development Workflows",
        "icon": "@tui.git-merge",
        "type": "checkbox",
        "order": 1,
        "items": [
          {
            "id": "gitflow",
            "label": "Gitflow",
            "filePath": "assets/pages/workflows/development/gitflow.json",
            "discouragedWith": [
              "trunk-based"
            ]
          },
          {
            "id": "trunk-based",
            "label": "Trunk Based",
            "filePath": "assets/pages/workflows/development/trunk-based.json",
            "discouragedWith": [
              "gitflow"
            ]
          }
        ]
      }
    ]
  }
};

export const GENERATED_PLATFORMS_CONFIG: Record<string, PlatformConfig> = {
  "antigravity": {
    "id": "antigravity",
    "content": "# {{ name }} Agent System Rules & Context\n\nYou are an expert AI assistant working on the **{{ name }}** project.\n\n## Project Context\n{{ description }}\n\n## Business Domains\nThis project operates in the following domains: {{ domains }}\n\n## Core Documentation Rules\nDo NOT guess architectural decisions or tech stack configurations. Instead, read the highly specific documentation in the `.agents/` folder depending on your current task:\n- **Skills**: Check `.agents/skills/` for specific engineering standards and architecture.\n- **Rules**: Check `.agents/rules/` for conventions, guidelines, and tooling.\n- **Workflows**: Check `.agents/workflows/` for step-by-step operational processes.\n\n## Documentation Update Policy (IMPORTANT)\nWhen the user tells you to \"commit\", \"save progress\", or \"update docs\" at the end of a session/task:\n1. You MUST update the central context file if one exists.\n2. If fundamental architectural rules or roadmap steps changed, update the corresponding skill or rule files to keep the global context perfectly synced.",
    "templates": {
      "skill": "---\nname: {{ name }}\ndescription: {{ description }}\n---\n\n# {{ name }}\n\n{{ content }}",
      "rule": "---\ntrigger: {{ trigger }}\ndescription: {{ description }}\n---\n\n{{ content }}",
      "workflow": "---\ndescription: {{ description }}\n---\n\n{{ content }}"
    }
  },
  "claude": {
    "id": "claude",
    "content": "# {{ name }} - Claude Project Instructions\n\nYou are Claude, an expert AI coding assistant assigned to the **{{ name }}** project.\n\n## Project Context\n{{ description }}\n\n## Business Domains\n{{ domains }}\n\n## Instructions & Knowledge Base\nThis project uses a structured knowledge base located in the `.claude/` directory:\n- **Skills**: Look in `.claude/skills/` for technical instructions and strict engineering standards.\n- **Rules**: Look in `.claude/rules/` for project conventions and structural constraints.\n- **Workflows**: Look in `.claude/workflows/` for specific tasks and operational procedures.\n\nBefore answering questions or writing code, ALWAYS review the relevant skills and rules to ensure architectural compliance. Do not hallucinate stack configurations.",
    "templates": {
      "skill": "---\nname: {{ name }}\ndescription: {{ description }}\n---\n\n# {{ name }}\n\n{{ content }}",
      "rule": "---\ntrigger: {{ trigger }}\ndescription: {{ description }}\n---\n\n{{ content }}",
      "workflow": "---\ndescription: {{ description }}\n---\n\n{{ content }}"
    }
  },
  "cursor": {
    "id": "cursor",
    "content": "You are an expert AI coding assistant for Cursor, working on the **{{ name }}** project.\n\n## Project Context\n{{ description }}\n**Business Domains**: {{ domains }}\n\n## Cursor Rules System\nThis project utilizes Cursor's `.mdc` rules system.\nAll architectural rules, skills, and workflows are located in the `.cursor/rules/` directory.\n\n- When generating or analyzing code, automatically apply the relevant rules based on their `globs` and descriptions.\n- Strictly adhere to the project's specific conventions as defined in the `.mdc` files.\n- Do not hallucinate architectural patterns. If a rule exists for a specific framework or domain, follow it exactly.",
    "templates": {
      "skill": "---\nname: {{ name }}\ndescription: {{ description }}\nglobs: {{ globs }}\n---\n\n# {{ name }}\n\n{{ content }}",
      "rule": "---\ndescription: {{ description }}\nglobs: {{ globs }}\n---\n\n{{ content }}",
      "workflow": "---\ndescription: {{ description }}\nglobs: *\n---\n\n{{ content }}"
    }
  }
};

export const ASSET_FILE_PATHS: Record<string, string> = {
  "express": "assets/pages/agents/backend/express.json",
  "nestjs": "assets/pages/agents/backend/nestjs.json",
  "php": "assets/pages/agents/backend/php.json",
  "spring-boot": "assets/pages/agents/backend/spring-boot.json",
  "clean-architecture": "assets/pages/agents/conventions/clean-architecture.json",
  "solid": "assets/pages/agents/conventions/solid.json",
  "mongodb": "assets/pages/agents/database/mongodb.json",
  "postgresql": "assets/pages/agents/database/postgresql.json",
  "redis": "assets/pages/agents/database/redis.json",
  "angular": "assets/pages/agents/frontend/angular.json",
  "javascript": "assets/pages/agents/frontend/javascript.json",
  "react": "assets/pages/agents/frontend/react.json",
  "typescript": "assets/pages/agents/frontend/typescript.json",
  "vue": "assets/pages/agents/frontend/vue.json",
  "flutter": "assets/pages/agents/mobile/flutter.json",
  "react-native": "assets/pages/agents/mobile/react-native.json",
  "swift": "assets/pages/agents/mobile/swift.json",
  "docker": "assets/pages/agents/tooling/docker.json",
  "github-actions": "assets/pages/agents/tooling/github-actions.json",
  "jest": "assets/pages/rules/tooling/jest.json",
  "strict-typing": "assets/pages/rules/code-quality/strict-typing.json",
  "zero-literals": "assets/pages/rules/code-quality/zero-literals.json",
  "clean-code": "assets/pages/rules/conventions/clean-code.json",
  "ddd": "assets/pages/rules/conventions/ddd.json",
  "fsd": "assets/pages/rules/conventions/fsd.json",
  "hexagonal": "assets/pages/rules/conventions/hexagonal.json",
  "mvc": "assets/pages/rules/conventions/mvc.json",
  "auth-guards": "assets/pages/rules/security/auth-guards.json",
  "xss-protection": "assets/pages/rules/security/xss-protection.json",
  "eslint": "assets/pages/rules/tooling/eslint.json",
  "husky": "assets/pages/rules/tooling/husky.json",
  "prettier": "assets/pages/rules/tooling/prettier.json",
  "vitest": "assets/pages/rules/tooling/vitest.json",
  "gitflow": "assets/pages/workflows/development/gitflow.json",
  "trunk-based": "assets/pages/workflows/development/trunk-based.json"
};

export const MAIN: Record<string, string> = {
  "antigravity": "assets/platforms/antigravity.json",
  "claude": "assets/platforms/claude.json",
  "cursor": "assets/platforms/cursor.json"
};

export const TEMPLATES: Record<string, string> = {
  "skill": "assets/platforms/cursor.json",
  "rule": "assets/platforms/cursor.json",
  "workflow": "assets/platforms/cursor.json"
};
